testing_mode = true
payment_provider = "stripe" #bmac if using Buy Me A Coffee
stripe_api_key_test = "rk_test_51PBODc2MUqczwlcLxO1KmPqvBHaDEUY1UTDBCEkjLnpW8IHn9k3oPUo6inuCv51MQ8KCYbtBkR31k4TRgwry5eHt002x20Q8oJ" #only needed if using Stripe
stripe_api_key = "sk_live_..." #only needed if using Stripe
stripe_link = "https://buy.stripe.com/..." #only needed if using Stripe
stripe_link_test = "https://buy.stripe.com/test_bIY4h62SO5LKfCM5kk" #only needed if using Stripe
client_id = "583031535943-5uvs2fnu37ei6m0c1bmv2cnhkv4k8hvm.apps.googleusercontent.com"
client_secret = "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"
redirect_url_test = 'http://localhost:8501/'
redirect_url = "https://your_app_url..."
bmac_api_key = "ey..." #only needed if using buy me a coffee
bmac_link = "https://www.buymeacoffee.com/..." #only needed if using buy me a coffee
